apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  labels:
    app: ngnx
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: ngnx
  template:
    metadata:
      labels:
        app: ngnx
    spec:
      containers:
      - name: ng
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: myvol1
      volumes:
      - name: myvol1
        hostPath: 
          path: /mnt1/out 
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: ngnx
  ports:
  - nodePort: 30008
    targetPort: 80
    port: 80
