apiVersion: v1
kind: Pod
metadata:
  name: test-ed
spec:
  containers:
    - name: test-contauiner
      image: k8s.gcr.io/test-webserver
      volumeMounts:
        - name: cacahe-volume
          mountPath: /cache
  volumes:
    - name: cacahe-volume
      emptyDir: {}        
