apiVersion: v1
kind: Pod
metadata: 
  name: redis1
  labels:
    app: myapp2
spec:
  containers:
    - name: redis
      image: redis
---
apiVersion: v1
kind: Service
metadata: 
  name: myservice2
spec:
  type: NodePort      
  ports:
    - targetPort: 80
      nodePort: 30009
      port: 80
  selector:
    app: myapp2
       
